[store]
# Store a report on test results
replay-dir = "target/nextest"

[profile.default]
status-level = "pass"
final-status-level = "fail"
failure-output = "immediate"
retries = 0

[profile.ci]
# Configuration for CI environments
fail-fast = true
retries = 2
status-level = "all"
final-status-level = "fail"
failure-output = "immediate-final"

[[profile.ci.overrides]]
filter = "test(test_context_search_functionality)"
retries = 0

# Profile for integration tests
[profile.integration]
retries = 1              # Retry once if a test fails (helps with flaky network tests)
test-threads = 1         # Single thread per test
status-level = "pass"
final-status-level = "fail"
failure-output = "immediate-final"

# Filter to only run integration tests
[[profile.integration.overrides]]
filter = "test(integration_tests::)"